name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up C++ environment
      uses: actions/setup-cpp@v1

    - name: Build project
      run: make all

    - name: Archive executables
      run: |
        mkdir -p release
        mv asm release/

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up MSVC
      uses: actions/setup-msvc@v1
      with:
        version: 2019

    - name: Build project
      run: msbuild /p:Configuration=Release

    - name: Archive executables
      run: |
        mkdir -p release
        mv asm.exe release/

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Linux Executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/asm
        asset_name: asm
        asset_content_type: application/octet-stream

    - name: Upload Windows Executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release/asm.exe
        asset_name: asm.exe
        asset_content_type: application/octet-stream
